version: "3.9"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend/nginx:latest
    networks:
      - internet
    ports:
      - "8000:80"
    restart: unless-stopped

  backend:
    image: "backend/node16-alpine"
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - internal-network
      - internet
    ports:
      - "9000:9000"
    depends_on:
      - database
    env_file:
      - backend/.env
    restart: unless-stopped

  database:
    image: "postgres:13"
    volumes:
      - "./postgres_data:/data/postgres"
    networks:
      - internal-network
    env_file:
      - backend/.env
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  postgres_data: